version: "3.9"
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
  redis:
    image: redis